/** Catálogo inicial (espelha o front mockData.procedures). */
export const proceduresCatalog = [
  {
    slug: 'lip-filler',
    name: 'Preenchimento Labial',
    description: 'Aumento e definição dos lábios com ácido hialurônico',
    icon: '💋',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
  },
  {
    slug: 'botox',
    name: 'Botox (Toxina Botulínica)',
    description: 'Suavização de rugas e linhas de expressão',
    icon: '✨',
    hasPoints: true,
    defaultPoints: 20,
    costPerPoint: 15,
    pricePerPoint: 45,
  },
  {
    slug: 'jawline',
    name: 'Contorno de Mandíbula',
    description: 'Definição e harmonização da linha da mandíbula',
    icon: '💎',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
  },
  {
    slug: 'cheek-filler',
    name: 'Preenchimento Malar',
    description: 'Volume e sustentação na região das maçãs do rosto',
    icon: '🌟',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
  },
  {
    slug: 'nose',
    name: 'Rinomodelação',
    description: 'Remodelação nasal sem cirurgia',
    icon: '👃',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
  },
];
