/** Catálogo inicial. `practiceProfileScope` separa lista da clínica (injetáveis/harmonização) da do cirurgião. */

/** Textos alinhados a `tipo_procedimento` no enhance (portal) e fallback em `enhanceDefaultRegions.js`. */
export const proceduresCatalog = [
  {
    slug: 'lip-filler',
    name: 'Preenchimento Labial',
    description: 'Aumento e definição dos lábios com ácido hialurônico',
    icon: '💋',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'lábios e contorno dos lábios',
  },
  {
    slug: 'botox',
    name: 'Botox (Toxina Botulínica)',
    description: 'Suavização de rugas e linhas de expressão',
    icon: '✨',
    hasPoints: true,
    defaultPoints: 20,
    costPerPoint: 15,
    pricePerPoint: 45,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'testa, glabela e região periorbital',
  },
  {
    slug: 'jawline',
    name: 'Contorno de Mandíbula',
    description: 'Definição e harmonização da linha da mandíbula',
    icon: '💎',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'mandíbula, ângulos da mandíbula e perfil inferior',
  },
  {
    slug: 'cheek-filler',
    name: 'Preenchimento Malar',
    description: 'Volume e sustentação na região das maçãs do rosto',
    icon: '🌟',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'maçãs do rosto e terço médio',
  },
  {
    slug: 'nose',
    name: 'Rinomodelação',
    description: 'Remodelação nasal sem cirurgia',
    icon: '👃',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'nariz e dorso nasal',
  },
  {
    slug: 'bigode-chines',
    name: 'Bigode chinês',
    description: 'Preenchimento do sulco nasogeniano (pregas ao redor do nariz e boca)',
    icon: '📐',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'sulco nasogeniano e linhas ao redor do nariz e boca',
  },
  {
    slug: 'mento',
    name: 'Mento (queixo)',
    description: 'Projeção e contorno do queixo com preenchimento ou harmonização',
    icon: '🔷',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'mento e contorno anterior do queixo',
  },
  {
    slug: 'olheira',
    name: 'Preenchimento de olheira',
    description: 'Correção de olheiras e sulco palpebral inferior com preenchimento',
    icon: '👁',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
    defaultEnhanceRegions: 'região infra-orbitária, sulco palpebral inferior e olheiras',
    isNew: true,
  },
  {
    slug: 'lipo-hd',
    name: 'Lipo HD',
    description: 'Lipoaspiração de alta definição.',
    icon: '💎',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'abdômen, flancos e definição de contornos corporais',
  },
  {
    slug: 'papada',
    name: 'Papada',
    description: 'Redução e contorno da região submentoniana.',
    icon: '✨',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'região submentoniana, pescoço e transição cervical',
  },
  {
    slug: 'lifting-braco',
    name: 'Lifting de braço',
    description: 'Correção de flacidez nos braços (braquioplastia).',
    icon: '💪',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'braços, terços médio e proximal e axilas',
  },
  {
    slug: 'mamoplastia-silicone',
    name: 'Mamoplastia',
    description: 'Aumento ou remodelação mamária — confirme prótese de silicone para simular.',
    icon: '💗',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'mamas',
  },
  {
    slug: 'rinoplastia',
    name: 'Rinoplastia',
    description: 'Cirurgia para alteração da forma do nariz.',
    icon: '👃',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'nariz, ponta nasal e dorso',
  },
  {
    slug: 'otoplastia',
    name: 'Otoplastia (orelha)',
    description: 'Correção estética das orelhas.',
    icon: '👂',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
    defaultEnhanceRegions: 'pavilhões auriculares e orelhas',
  },
];
