/** Catálogo inicial. `practiceProfileScope` separa lista da clínica (injetáveis/harmonização) da do cirurgião. */
export const proceduresCatalog = [
  {
    slug: 'lip-filler',
    name: 'Preenchimento Labial',
    description: 'Aumento e definição dos lábios com ácido hialurônico',
    icon: '💋',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'botox',
    name: 'Botox (Toxina Botulínica)',
    description: 'Suavização de rugas e linhas de expressão',
    icon: '✨',
    hasPoints: true,
    defaultPoints: 20,
    costPerPoint: 15,
    pricePerPoint: 45,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'jawline',
    name: 'Contorno de Mandíbula',
    description: 'Definição e harmonização da linha da mandíbula',
    icon: '💎',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'cheek-filler',
    name: 'Preenchimento Malar',
    description: 'Volume e sustentação na região das maçãs do rosto',
    icon: '🌟',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'nose',
    name: 'Rinomodelação',
    description: 'Remodelação nasal sem cirurgia',
    icon: '👃',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'bigode-chines',
    name: 'Bigode chinês',
    description: 'Preenchimento do sulco nasogeniano (pregas ao redor do nariz e boca)',
    icon: '📐',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'mento',
    name: 'Mento (queixo)',
    description: 'Projeção e contorno do queixo com preenchimento ou harmonização',
    icon: '🔷',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'clinic',
  },
  {
    slug: 'lipo-hd',
    name: 'Lipo HD',
    description: 'Lipoaspiração de alta definição.',
    icon: '💎',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
  {
    slug: 'papada',
    name: 'Papada',
    description: 'Redução e contorno da região submentoniana.',
    icon: '✨',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
  {
    slug: 'lifting-braco',
    name: 'Lifting de braço',
    description: 'Correção de flacidez nos braços (braquioplastia).',
    icon: '💪',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
  {
    slug: 'mamoplastia-silicone',
    name: 'Mamoplastia',
    description: 'Aumento ou remodelação mamária — confirme prótese de silicone para simular.',
    icon: '💗',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
  {
    slug: 'rinoplastia',
    name: 'Rinoplastia',
    description: 'Cirurgia para alteração da forma do nariz.',
    icon: '👃',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
  {
    slug: 'otoplastia',
    name: 'Otoplastia (orelha)',
    description: 'Correção estética das orelhas.',
    icon: '👂',
    hasPoints: false,
    defaultPoints: 0,
    costPerPoint: 0,
    pricePerPoint: 0,
    practiceProfileScope: 'surgeon',
  },
];
